### ISSUE TITLE
The Cataclysm divination card loot

### ISSUE THREAD

**Issue by markliu06** [Project-Path-of-Exile-Wiki/wiki#50] opened 2021-08-30 23:59 UTC
## Bug -

The wiki module that generated the loot of The Cataclysm divination need update. The card did not grant Vaal gem anymore since 3.14

## Reproduction steps

https://www.poewiki.net/wiki/The_Cataclysm

## Expected outcome

Should shown every active skill gem with spell gem tag, but does not contain gem that did not have level 21, or have vaal in the name

## Actual outcome

Current shown vaal gem

## Environment
- Edge

## Perceived impact

5

## Screenshots
![Screenshot 2021-08-31 075846](https://user-images.githubusercontent.com/67254854/131420663-70197a0f-8816-4aec-8a67-4a4a72dfdd5a.png)

**Comment by acbeaumo** [comment] 2021-09-10 15:41
Assign this to me please.

**Comment by acbeaumo** [comment] 2021-09-10 16:51
It looks like this also applies to the following divination cards: The Wilted Rose, The Summoner, The Fox, Gemcutter's Promise and Deathly Designs.

**Comment by acbeaumo** [comment] 2021-09-10 22:06
The Cataclysm can return support gems too, right?

**Comment by markliu06** [comment] 2021-09-11 04:58
> The Cataclysm can return support gems too, right?

Probably. https://www.poewiki.net/wiki/Category:Spell_(gem_tag)

But i haven't spam the card to check the actual in-game loot

**Comment by markliu06** [comment] 2021-09-11 05:03
> It looks like this also applies to the following divination cards: The Wilted Rose, The Summoner, The Fox, Gemcutter's Promise and Deathly Designs.

Well. Should open more bug report or just stick to this one

I never edit the auto upgrade myself but probably it is stored in

https://www.poewiki.net/wiki/Module:Item2/upgrade

**Comment by acbeaumo** [comment] 2021-09-11 05:53
> I never edit the auto upgrade myself but probably it is stored in
> 
> https://www.poewiki.net/wiki/Module:Item2/upgrade

I updated it earlier. I'm just not sure about the support gems.

**Comment by markliu06** [comment] 2021-09-11 06:04
For The Summoner, just checked , i think it should not have awakened gem

**Comment by acbeaumo** [comment] 2021-09-13 11:18
I can't close this issue until it is confirmed that The Cataclysm cannot return support gems.

**Comment by markliu06** [comment] 2021-09-13 11:24
Well, no luck to buy this card for cheap and i only have 3 left in perma league

**Comment by markliu06** [comment] 2021-10-05 13:34
Two attempts today: Summon Lighting Golem and Winter Orb

There is 160 active skill gem with Spell gem tag (including Detonate Mines, Portal and Blood and Sand), and only 19 support gems with this tag

I think i need a large sample size to say no, as p = 19/(160+19-3), need a way larger sample size than 2 to have 70% or 99% confidence (and the rest has returned to uni professor)

**Comment by Journeytojah** [comment] 2021-11-07 06:21
This might be something the Divcord could help with. I’ll try to reach them.

**Comment by acbeaumo** [comment] 2022-06-06 13:37
This confirms that Dying Anguish can return support gems: https://youtu.be/ym5m1SrZN2s?t=373 Therefore, it follows that it should also be possible to get support gems from the Cataclysm.

I'm closing this issue noting that the stated expected outcome is incorrect. The Cataclysm can return skill gems _and_ support gems, as long as they're not drop restricted.

**Closed by acbeaumo** 2022-06-06 13:37 UTC
Labels: on hold, needs more info
